V?= 0

ifeq ($(V),1)
VCC:=
VAS:=
VCXX:=
VDEP:=
VLD:=
VAR:=
VRES:=
VCCLD:=
VCXLD:=
VSTRP:=
VINST:=
VMD:=
VCFG:=
VGEN:=
VGIT:=
VSUB:=
VRM:=
VRMDR:=
VR:=
else
VCC=	@echo $(EQT)   $(ZIMK__PRBOLD)$(ZIMK__PRLCYAN)[CC]$(ZIMK__PRNORM)   $@$(EQT)
VAS=	@echo $(EQT)   $(ZIMK__PRBOLD)$(ZIMK__PRLCYAN)[AS]$(ZIMK__PRNORM)   $@$(EQT)
VCXX=	@echo $(EQT)   $(ZIMK__PRBOLD)$(ZIMK__PRLCYAN)[CXX]$(ZIMK__PRNORM)  $@$(EQT)
VDEP=	@echo $(EQT)   $(ZIMK__PRBOLD)$(ZIMK__PRWHITE)[DEP]$(ZIMK__PRNORM)  $@$(EQT)
VLD=	@echo $(EQT)   $(ZIMK__PRBOLD)$(ZIMK__PRWHITE)[LD]$(ZIMK__PRNORM)   $@$(EQT)
VAR=	@echo $(EQT)   $(ZIMK__PRBOLD)$(ZIMK__PRLGREEN)[AR]   $@$(ZIMK__PRNORM)$(EQT)
VRES=   @echo $(EQT)   $(ZIMK__PRBOLD)$(ZIMK__PRLCYAN)[RES]$(ZIMK__PRNORM)  $@$(EQT)
VCCLD=	@echo $(EQT)   $(ZIMK__PRBOLD)$(ZIMK__PRLGREEN)[CCLD]$(ZIMK__PRNORM) $(ZIMK__PRGREEN)$@$(ZIMK__PRNORM)$(EQT)
VCXLD=	@echo $(EQT)   $(ZIMK__PRBOLD)$(ZIMK__PRLGREEN)[CXLD]$(ZIMK__PRNORM) $(ZIMK__PRGREEN)$@$(ZIMK__PRNORM)$(EQT)
VSTRP=  @echo $(EQT)   $(ZIMK__PRBOLD)$(ZIMK__PRWHITE)[STRP]$(ZIMK__PRNORM) $<$(EQT)
VINST=	@echo $(EQT)   $(ZIMK__PRBOLD)$(ZIMK__PRLMAGENTA)[INST]$(ZIMK__PRNORM) $(ZIMK__PRMAGENTA)$(_ZIMK_0)$(ZIMK__PRNORM)$(EQT)
VMD=	@echo $(EQT)   $(ZIMK__PRBOLD)$(ZIMK__PRWHITE)[MD]$(ZIMK__PRNORM)   $@$(EQT)
VCFG=	@echo $(EQT)   $(ZIMK__PRBOLD)$(ZIMK__PRWHITE)[CFG]$(ZIMK__PRNORM)  $<$(EQT)
VGEN=	@echo $(EQT)   $(ZIMK__PRBOLD)$(ZIMK__PRWHITE)[GEN]$(ZIMK__PRNORM)  $@$(EQT)
VGIT=	@echo $(EQT)   $(ZIMK__PRBOLD)$(ZIMK__PRWHITE)[GIT]$(ZIMK__PRNORM)  $@$(EQT)
VSUB=	@echo $(EQT)   $(ZIMK__PRBOLD)$(ZIMK__PRWHITE)[SUB]$(ZIMK__PRNORM)  $@$(EQT)
VRM=	@echo $(EQT)   $(ZIMK__PRBOLD)$(ZIMK__PRLRED)[RM]   $(ZIMK__PRNORM)$(ZIMK__PRRED)$(_ZIMK_0)$(ZIMK__PRNORM)$(EQT)
VRMDR=	@echo $(EQT)   $(ZIMK__PRBOLD)$(ZIMK__PRLRED)[RMDR] $(ZIMK__PRNORM)$(ZIMK__PRLRED)$(_ZIMK_0)$(ZIMK__PRNORM)$(EQT)
VR:=	@
endif

# vim: noet:si:ts=8:sts=8:sw=8
